const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, '..', 'commands');

const helper = `const isGroup = jid => typeof jid === 'string' && jid.endsWith('@g.us');
const senderOf = msg => msg.key.participant || msg.key.remoteJid;
async function context(sock, msg, sudoOnly = false) {
  const jid = msg.key.remoteJid;
  if (!isGroup(jid)) { await sock.sendMessage(jid, { text: '❌ Cette commande est réservée aux groupes.' }); return null; }
  const meta = await sock.groupMetadata(jid);
  const sender = senderOf(msg);
  const admin = meta.participants.find(p => p.id === sender)?.admin;
  if (sudoOnly ? !global.isSudo(sender) : (!admin && !global.isSudo(sender))) {
    await sock.sendMessage(jid, { text: sudoOnly ? '❌ SUDO uniquement.' : '❌ Admin ou SUDO requis.' }); return null;
  }
  const botId = sock.user.id.split(':')[0] + '@s.whatsapp.net';
  if (!meta.participants.find(p => p.id === botId)?.admin) { await sock.sendMessage(jid, { text: '❌ Le bot doit être administrateur.' }); return null; }
  return { jid, meta, sender, botId };
}
function targets(msg, args = []) {
  const ci = msg.message?.extendedTextMessage?.contextInfo;
  if (ci?.mentionedJid?.length) return ci.mentionedJid;
  if (ci?.participant) return [ci.participant];
  return args.filter(Boolean).map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net');
}
module.exports = { context, targets };
`;
fs.writeFileSync(path.join(out, '_group-utils.js'), helper);

const defs = [
['demoteall','Rétrograde tous les administrateurs sauf le bot et les SUDO.',`const { context } = require('./_group-utils'); module.exports={name:'demoteall',description:'Rétrograde les admins non protégés.',execute:async(sock,msg)=>{const c=await context(sock,msg,true);if(!c)return;const ids=c.meta.participants.filter(p=>p.admin&&p.id!==c.botId&&!global.isSudo(p.id)).map(p=>p.id);if(ids.length)await sock.groupParticipantsUpdate(c.jid,ids,'demote');await sock.sendMessage(c.jid,{text:'✅ '+ids.length+' administrateur(s) rétrogradé(s).'});}};`],
['promotehere','Promut tous les membres mentionnés ou ciblés par réponse.',`const { context, targets } = require('./_group-utils'); module.exports={name:'promotehere',description:'Promut plusieurs membres ciblés.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const ids=targets(msg,args).filter(id=>!global.isSudo(id));if(!ids.length)return sock.sendMessage(c.jid,{text:'❌ Mentionnez ou répondez à un membre.'});await sock.groupParticipantsUpdate(c.jid,ids,'promote');await sock.sendMessage(c.jid,{text:'✅ Membres ciblés promus.'});}};`],
['demotehere','Rétrograde tous les membres mentionnés ou ciblés par réponse.',`const { context, targets } = require('./_group-utils'); module.exports={name:'demotehere',description:'Rétrograde plusieurs membres ciblés.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const ids=targets(msg,args);if(!ids.length)return sock.sendMessage(c.jid,{text:'❌ Mentionnez ou répondez à un admin.'});await sock.groupParticipantsUpdate(c.jid,ids,'demote');await sock.sendMessage(c.jid,{text:'✅ Membres ciblés rétrogradés.'});}};`],
['setrules','Enregistre les règles du groupe dans un fichier local.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'setrules',description:'Définit les règles du groupe.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;if(!args.length)return sock.sendMessage(c.jid,{text:'Usage: .setrules vos règles'});const f=path.join(__dirname,'..','data','group-rules.json');fs.mkdirSync(path.dirname(f),{recursive:true});let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}d[c.jid]=args.join(' ');fs.writeFileSync(f,JSON.stringify(d,null,2));await sock.sendMessage(c.jid,{text:'✅ Règles enregistrées.'});}};`],
['rules','Affiche les règles enregistrées du groupe.',`const fs=require('fs');const path=require('path');module.exports={name:'rules',description:'Affiche les règles du groupe.',execute:async(sock,msg)=>{const f=path.join(__dirname,'..','data','group-rules.json');let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}await sock.sendMessage(msg.key.remoteJid,{text:'📜 *RÈGLES DU GROUPE*\\n\\n'+(d[msg.key.remoteJid]||'Aucune règle configurée.')});}};`],
['welcome','Active ou désactive le mode bienvenue du groupe.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'welcome',description:'Configure le mode bienvenue.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const f=path.join(__dirname,'..','data','group-settings.json');fs.mkdirSync(path.dirname(f),{recursive:true});let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}d[c.jid]={...(d[c.jid]||{}),welcome:args[0]==='on'};fs.writeFileSync(f,JSON.stringify(d,null,2));await sock.sendMessage(c.jid,{text:'✅ Bienvenue '+(args[0]==='on'?'activé':'désactivé')+'.'});}};`],
['goodbye','Active ou désactive le message de départ.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'goodbye',description:'Configure le mode départ.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const f=path.join(__dirname,'..','data','group-settings.json');fs.mkdirSync(path.dirname(f),{recursive:true});let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}d[c.jid]={...(d[c.jid]||{}),goodbye:args[0]==='on'};fs.writeFileSync(f,JSON.stringify(d,null,2));await sock.sendMessage(c.jid,{text:'✅ Départ automatique '+(args[0]==='on'?'activé':'désactivé')+'.'});}};`],
['slowmode','Active un délai logique entre les actions de modération.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'slowmode',description:'Configure le mode anti-rafale.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const seconds=Math.max(0,Math.min(300,Number(args[0])||0));const f=path.join(__dirname,'..','data','group-settings.json');fs.mkdirSync(path.dirname(f),{recursive:true});let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}d[c.jid]={...(d[c.jid]||{}),slowmode:seconds};fs.writeFileSync(f,JSON.stringify(d,null,2));await sock.sendMessage(c.jid,{text:'✅ Slowmode réglé à '+seconds+' seconde(s).'});}};`],
['lockmedia','Active ou désactive la politique médias.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'lockmedia',description:'Configure la politique médias.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const f=path.join(__dirname,'..','data','group-settings.json');fs.mkdirSync(path.dirname(f),{recursive:true});let d={};try{d=JSON.parse(fs.readFileSync(f))}catch{}d[c.jid]={...(d[c.jid]||{}),lockmedia:args[0]==='on'};fs.writeFileSync(f,JSON.stringify(d,null,2));await sock.sendMessage(c.jid,{text:'✅ Médias '+(args[0]==='on'?'restreints':'autorisés')+'.'});}};`],
['slowannounce','Programme un rappel administratif après un délai en minutes.',`const {context}=require('./_group-utils');module.exports={name:'slowannounce',description:'Programme un rappel dans le groupe.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const mins=Math.max(1,Math.min(1440,Number(args[0])||0));const text=args.slice(1).join(' ')||'Rappel administratif.';if(!mins)return sock.sendMessage(c.jid,{text:'Usage: .slowannounce minutes message'});await sock.sendMessage(c.jid,{text:'✅ Rappel programmé dans '+mins+' minute(s).'});setTimeout(()=>sock.sendMessage(c.jid,{text:'⏰ *RAPPEL*\\n'+text}).catch(()=>{}),mins*60000);}};`],
['snapshot','Sauvegarde localement les métadonnées du groupe.',`const fs=require('fs');const path=require('path');const {context}=require('./_group-utils');module.exports={name:'snapshot',description:'Sauvegarde la configuration du groupe.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const f=path.join(__dirname,'..','data','snapshots');fs.mkdirSync(f,{recursive:true});fs.writeFileSync(path.join(f,encodeURIComponent(c.jid)+'.json'),JSON.stringify({subject:c.meta.subject,desc:c.meta.desc,participants:c.meta.participants,at:new Date().toISOString()},null,2));await sock.sendMessage(c.jid,{text:'✅ Instantané du groupe sauvegardé.'});}};`],
['auditadmins','Affiche un audit des administrateurs et de leurs droits.',`const {context}=require('./_group-utils');module.exports={name:'auditadmins',description:'Audite les administrateurs du groupe.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const admins=c.meta.participants.filter(p=>p.admin);const lines=admins.map(p=>'• @'+p.id.split('@')[0]+' — '+p.admin).join('\\n');await sock.sendMessage(c.jid,{text:'🔎 *AUDIT ADMINS*\\n'+lines,mentions:admins.map(p=>p.id)});}};`],
['membercount','Affiche les statistiques de membres et d’administrateurs.',`const {context}=require('./_group-utils');module.exports={name:'membercount',description:'Affiche les statistiques du groupe.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const admins=c.meta.participants.filter(p=>p.admin).length;await sock.sendMessage(c.jid,{text:'📊 Membres : '+c.meta.participants.length+'\\n👑 Admins : '+admins+'\\n👤 Membres ordinaires : '+(c.meta.participants.length-admins)});}};`],
['randommember','Tire au sort un membre du groupe.',`const {context}=require('./_group-utils');module.exports={name:'randommember',description:'Tire un membre au sort.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const list=c.meta.participants.filter(p=>p.id!==c.botId);if(!list.length)return;const pick=list[Math.floor(Math.random()*list.length)].id;await sock.sendMessage(c.jid,{text:'🎲 Membre tiré au sort : @'+pick.split('@')[0],mentions:[pick]});}};`],
['rotateadmin','Tire un administrateur de permanence.',`const {context}=require('./_group-utils');module.exports={name:'rotateadmin',description:'Tire un admin de permanence.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const list=c.meta.participants.filter(p=>p.admin);if(!list.length)return;const pick=list[Math.floor(Math.random()*list.length)].id;await sock.sendMessage(c.jid,{text:'🛡️ Admin de permanence : @'+pick.split('@')[0],mentions:[pick]});}};`],
['silenttag','Mentionne un membre avec une notification discrète.',`const {context,targets}=require('./_group-utils');module.exports={name:'silenttag',description:'Mentionne discrètement une cible.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const ids=targets(msg,args);if(!ids.length)return sock.sendMessage(c.jid,{text:'Usage: .silenttag @membre'});await sock.sendMessage(c.jid,{text:'‎',mentions:ids});}};`],
['mentionadmins','Mentionne les admins avec un message personnalisé.',`const {context}=require('./_group-utils');module.exports={name:'mentionadmins',description:'Mentionne les admins avec un message.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const ids=c.meta.participants.filter(p=>p.admin).map(p=>p.id);await sock.sendMessage(c.jid,{text:args.join(' ')||'Attention des administrateurs requise.',mentions:ids});}};`],
['grouphealth','Produit un diagnostic de santé du groupe.',`const {context}=require('./_group-utils');module.exports={name:'grouphealth',description:'Diagnostique la configuration du groupe.',execute:async(sock,msg)=>{const c=await context(sock,msg);if(!c)return;const adminCount=c.meta.participants.filter(p=>p.admin).length;const score=Math.max(0,Math.min(100,50+(adminCount>0?25:0)+(c.meta.restrict?15:0)+(c.meta.announce?10:0)));await sock.sendMessage(c.jid,{text:'🩺 *SANTÉ DU GROUPE*\\nScore : '+score+'/100\\nAdmins : '+adminCount+'\\nÉcriture restreinte : '+(c.meta.announce?'oui':'non')});}};`],
['emergencylock','Ferme immédiatement le groupe et prévient les membres.',`const {context}=require('./_group-utils');module.exports={name:'emergencylock',description:'Active le verrouillage d’urgence.',execute:async(sock,msg)=>{const c=await context(sock,msg,true);if(!c)return;await sock.groupSettingUpdate(c.jid,'announcement');await sock.sendMessage(c.jid,{text:'🚨 VERROUILLAGE D’URGENCE ACTIVÉ. Seuls les admins peuvent écrire.'});}};`],
['emergencyunlock','Rouvre immédiatement le groupe.',`const {context}=require('./_group-utils');module.exports={name:'emergencyunlock',description:'Désactive le verrouillage d’urgence.',execute:async(sock,msg)=>{const c=await context(sock,msg,true);if(!c)return;await sock.groupSettingUpdate(c.jid,'not_announcement');await sock.sendMessage(c.jid,{text:'🔓 VERROUILLAGE D’URGENCE DÉSACTIVÉ.'});}};`],
['membercard','Affiche la fiche d’un membre mentionné ou ciblé.',`const {context,targets}=require('./_group-utils');module.exports={name:'membercard',description:'Affiche une fiche membre.',execute:async(sock,msg,args)=>{const c=await context(sock,msg);if(!c)return;const id=targets(msg,args)[0];if(!id)return sock.sendMessage(c.jid,{text:'❌ Mentionnez un membre ou répondez à son message.'});const p=c.meta.participants.find(x=>x.id===id);await sock.sendMessage(c.jid,{text:'🪪 *FICHE MEMBRE*\\nJID : '+id+'\\nRôle : '+(p?.admin||'membre')+'\\nSUDO : '+(global.isSudo(id)?'oui':'non'),mentions:[id]});}};`]
];

for (const [name, desc, code] of defs) fs.writeFileSync(path.join(out, name+'.js'), code.replace(/\\u001b\[32m|\\u001b\[0m/g, ''));
console.log('Créées:', defs.map(d=>d[0]).join(', '));
